spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marry_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: MyPassword@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin
  profiles:
    active: prod


app:
  jwt:
    secret: marrySecretKey2024VeryLongSecretKeyForJWTTokenGeneration
    expiration: 86400000  # 24 hours in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.xly.marry: DEBUG
    org.springframework.security: DEBUG